services:
  kptv-promax:
    #image: ghcr.io/kpirnie/kptv-restreamer:latest
    image: localhost/kptest:latest
    container_name: kptv_promax
    hostname: kptv_promnax
    restart: unless-stopped
    ports:
      - 9000:8080
    volumes:
      - ./config:/app/config:ro
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
