services:
  kptest:
    #image: ghcr.io/kpirnie/kptv-restreamer:latest
    image: localhost/kptest:latest
    container_name: kptest
    hostname: kptest
    restart: unless-stopped
    ports:
      - 9000:8080
    volumes:
      - ./config:/app/config:ro
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
